(cl:defpackage my_srv-srv
  (:use )
  (:export
   "HARMONIC"
   "<HARMONIC-REQUEST>"
   "HARMONIC-REQUEST"
   "<HARMONIC-RESPONSE>"
   "HARMONIC-RESPONSE"
   "VELOCITY"
   "<VELOCITY-REQUEST>"
   "VELOCITY-REQUEST"
   "<VELOCITY-RESPONSE>"
   "VELOCITY-RESPONSE"
  ))

