// Generated by gencpp from file my_srv/Harmonic.msg
// DO NOT EDIT!


#ifndef MY_SRV_MESSAGE_HARMONIC_H
#define MY_SRV_MESSAGE_HARMONIC_H

#include <ros/service_traits.h>


#include <my_srv/HarmonicRequest.h>
#include <my_srv/HarmonicResponse.h>


namespace my_srv
{

struct Harmonic
{

typedef HarmonicRequest Request;
typedef HarmonicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Harmonic
} // namespace my_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_srv::Harmonic > {
  static const char* value()
  {
    return "462c9efca65962aab169b08e0e822b8b";
  }

  static const char* value(const ::my_srv::Harmonic&) { return value(); }
};

template<>
struct DataType< ::my_srv::Harmonic > {
  static const char* value()
  {
    return "my_srv/Harmonic";
  }

  static const char* value(const ::my_srv::Harmonic&) { return value(); }
};


// service_traits::MD5Sum< ::my_srv::HarmonicRequest> should match 
// service_traits::MD5Sum< ::my_srv::Harmonic > 
template<>
struct MD5Sum< ::my_srv::HarmonicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_srv::Harmonic >::value();
  }
  static const char* value(const ::my_srv::HarmonicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_srv::HarmonicRequest> should match 
// service_traits::DataType< ::my_srv::Harmonic > 
template<>
struct DataType< ::my_srv::HarmonicRequest>
{
  static const char* value()
  {
    return DataType< ::my_srv::Harmonic >::value();
  }
  static const char* value(const ::my_srv::HarmonicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_srv::HarmonicResponse> should match 
// service_traits::MD5Sum< ::my_srv::Harmonic > 
template<>
struct MD5Sum< ::my_srv::HarmonicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_srv::Harmonic >::value();
  }
  static const char* value(const ::my_srv::HarmonicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_srv::HarmonicResponse> should match 
// service_traits::DataType< ::my_srv::Harmonic > 
template<>
struct DataType< ::my_srv::HarmonicResponse>
{
  static const char* value()
  {
    return DataType< ::my_srv::Harmonic >::value();
  }
  static const char* value(const ::my_srv::HarmonicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SRV_MESSAGE_HARMONIC_H
