// Generated by gencpp from file my_srv/HarmonicResponse.msg
// DO NOT EDIT!


#ifndef MY_SRV_MESSAGE_HARMONICRESPONSE_H
#define MY_SRV_MESSAGE_HARMONICRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_srv
{
template <class ContainerAllocator>
struct HarmonicResponse_
{
  typedef HarmonicResponse_<ContainerAllocator> Type;

  HarmonicResponse_()
    : vel(0.0)  {
    }
  HarmonicResponse_(const ContainerAllocator& _alloc)
    : vel(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::my_srv::HarmonicResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_srv::HarmonicResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HarmonicResponse_

typedef ::my_srv::HarmonicResponse_<std::allocator<void> > HarmonicResponse;

typedef boost::shared_ptr< ::my_srv::HarmonicResponse > HarmonicResponsePtr;
typedef boost::shared_ptr< ::my_srv::HarmonicResponse const> HarmonicResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_srv::HarmonicResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_srv::HarmonicResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_srv::HarmonicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_srv::HarmonicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_srv::HarmonicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_srv::HarmonicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_srv::HarmonicResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_srv::HarmonicResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_srv::HarmonicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "378ca590f55ecb8d30867c8ddf1db3c5";
  }

  static const char* value(const ::my_srv::HarmonicResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x378ca590f55ecb8dULL;
  static const uint64_t static_value2 = 0x30867c8ddf1db3c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_srv::HarmonicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_srv/HarmonicResponse";
  }

  static const char* value(const ::my_srv::HarmonicResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_srv::HarmonicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vel\n\
\n\
";
  }

  static const char* value(const ::my_srv::HarmonicResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_srv::HarmonicResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HarmonicResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_srv::HarmonicResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_srv::HarmonicResponse_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SRV_MESSAGE_HARMONICRESPONSE_H
