// Generated by gencpp from file assignment1_srv/Rand_TargetRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_SRV_MESSAGE_RAND_TARGETREQUEST_H
#define ASSIGNMENT1_SRV_MESSAGE_RAND_TARGETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1_srv
{
template <class ContainerAllocator>
struct Rand_TargetRequest_
{
  typedef Rand_TargetRequest_<ContainerAllocator> Type;

  Rand_TargetRequest_()
    {
    }
  Rand_TargetRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Rand_TargetRequest_

typedef ::assignment1_srv::Rand_TargetRequest_<std::allocator<void> > Rand_TargetRequest;

typedef boost::shared_ptr< ::assignment1_srv::Rand_TargetRequest > Rand_TargetRequestPtr;
typedef boost::shared_ptr< ::assignment1_srv::Rand_TargetRequest const> Rand_TargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment1_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1_srv/Rand_TargetRequest";
  }

  static const char* value(const ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rand_TargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::assignment1_srv::Rand_TargetRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_SRV_MESSAGE_RAND_TARGETREQUEST_H
