// Generated by gencpp from file assignment1_srv/Rand_TargetResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_SRV_MESSAGE_RAND_TARGETRESPONSE_H
#define ASSIGNMENT1_SRV_MESSAGE_RAND_TARGETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1_srv
{
template <class ContainerAllocator>
struct Rand_TargetResponse_
{
  typedef Rand_TargetResponse_<ContainerAllocator> Type;

  Rand_TargetResponse_()
    : pos_x(0.0)
    , pos_y(0.0)  {
    }
  Rand_TargetResponse_(const ContainerAllocator& _alloc)
    : pos_x(0.0)
    , pos_y(0.0)  {
  (void)_alloc;
    }



   typedef double _pos_x_type;
  _pos_x_type pos_x;

   typedef double _pos_y_type;
  _pos_y_type pos_y;





  typedef boost::shared_ptr< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Rand_TargetResponse_

typedef ::assignment1_srv::Rand_TargetResponse_<std::allocator<void> > Rand_TargetResponse;

typedef boost::shared_ptr< ::assignment1_srv::Rand_TargetResponse > Rand_TargetResponsePtr;
typedef boost::shared_ptr< ::assignment1_srv::Rand_TargetResponse const> Rand_TargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment1_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c67b91aaf77683572cc7fbcbee54643";
  }

  static const char* value(const ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c67b91aaf776835ULL;
  static const uint64_t static_value2 = 0x72cc7fbcbee54643ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1_srv/Rand_TargetResponse";
  }

  static const char* value(const ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pos_x\n\
float64 pos_y\n\
\n\
";
  }

  static const char* value(const ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
      stream.next(m.pos_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rand_TargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1_srv::Rand_TargetResponse_<ContainerAllocator>& v)
  {
    s << indent << "pos_x: ";
    Printer<double>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<double>::stream(s, indent + "  ", v.pos_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_SRV_MESSAGE_RAND_TARGETRESPONSE_H
